module.exports = {
    eventsAround: "🔍  События вокруг меня",
    eventsAroundRetry: "🔍  Попробовать еще раз",
    eventsToday: "📅  События на сегодня",
    eventsTodayRetry: "📅  Попробовать еще раз",
    home: "🏠  Домой",
    feelingLucky: "🍀  Мне сегодня повезет!",
    locationRequest: markup => markup.locationRequestButton("🌍  Отправить мое местоположение"),
    near: "🎯  Неподалеку",
    walk: "🚶‍♂️  Готов прогуляться",
    subscribe: "✉️  Подписаться",
    unsubscribe: "✉️  Отписаться",
    preferences: "⚙️  Предпочтения",
    confirmSubscription: "👌  Продолжаем",
    digestsEveryDay: "⚡️  Каждый день",
    digestsEveryWeekday: "🚀  По будним дням",
    digestsBeforeWeekend: "🎉  Пятница + выходные",
    configureEntry: "🚪  Тип входа",
    configureType: "🌱  Тип событий",
    educationEvents: "🥇  Развивающие",
    entertainmentEvents: "🎈  Развлекательные",
    allTypesEvents: "🥇🎈  Все подряд",
    freeEvents: "🧀  Свободный вход",
    paidEvents: "💰  Платный вход",
    allEntryTypesEvents: "🧀💰  Без разницы",
};